### ISSUE TITLE
Gelecek eğitimler?

### ISSUE THREAD

**Issue by smehemmed** [PauEducation/pau-egitim-programi#20]
* Eğitimlerin devamı olacak mı?

**Comment by arslanbilal** [comment]
Eğitimler vizeden sonra devam edecektir. Ayrıca eğitim programı eğitim grubu arasında konuşulup, organizasyon reposu facebook da paylaşılacaktır.

**Comment by arslanbilal** [comment]
asagidaki issue da tarsiliyor. Hala ilgileniyorsan, goz atmanda yarar var. 
link: https://github.com/PauEducation/work-shops-determination/issues/1
