### ISSUE TITLE
Images from the 19 October week

### ISSUE THREAD

**Issue by barankurtulusozan** [PauEducation/pau-egitim-programi#6]
![12179088_10153477946357745_1782093368_n](https://cloud.githubusercontent.com/assets/9303862/10725507/3737bf44-7bd5-11e5-8109-6a564274b7da.jpg)
![Uploading 12179013_10153477942567745_1615886322_n.jpg…]()
![12179589_10153477941617745_616363290_n](https://cloud.githubusercontent.com/assets/9303862/10725506/3737688c-7bd5-11e5-8a13-28497267a2c2.jpg)
![Uploading 12181993_10207487538562327_1928485349_n.jpg…]()

**Comment by barankurtulusozan** [comment]
![12179013_10153477942567745_1615886322_n](https://cloud.githubusercontent.com/assets/9303862/10725523/4c5f9e50-7bd5-11e5-87d4-24c6ad088f28.jpg)
![12181993_10207487538562327_1928485349_n](https://cloud.githubusercontent.com/assets/9303862/10725524/4c626a72-7bd5-11e5-80aa-a3b70ce4634e.jpg)

**Comment by arslanbilal** [comment]
Thanks for images. Added relevant lecture files
